# this is list this is mutable we can store multiple no of element and we can change it also ,it is denoted uner[]
l1=[1,"shaurya","good",4,True,89,]
print(l1)
print(type(l1))
print(l1[2])
print(l1[-1])
print(l1[2:5])
l1[0]=69
print(l1)
l1.append("joke")
print(l1)
l1.pop()
print(l1)
l1.reverse()
print(l1)
l1.insert(3,"lol")
print(l1)
l2=["apple","banana","coconut","mango","pineapple","guava","strawberry"]
l2.sort()
print(l2)
print(l1+l2)
print(l2+l1)
print(l1*3+l2)
# the dictonary is a unorderd list of collection of data and and key value pair, the list and tuple are the ordered list of collection
show={'asur':10,'patalok':11,'mirzapur':12,'night':13,'groot':14}
print(show)
print(type(show))
print(show.keys())
print(show.values())
show["boys"]=16
print(show)
show["boys"]=15
print(show)
movie={'omg':20,'gadar':21,'pirate':22,'shuitcase':23}
print(movie)
show.update(movie)
print(show)
show.pop("gadar")
print(show)